# Use offical Node.js image based on Debian to get glibc, compatible with SWC.
FROM node:22-slim

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .

EXPOSE 5173

# Lauch Vite in dev mode
CMD ["npm", "run", "dev", "--", "--host"]