services:
  frontend:
    build:
      context: frontend
      dockerfile: docker/Dockerfile-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=development
