services:
  frontend:
    build:
      context: frontend
      dockerfile: docker/Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=development