networks:
  my-network:
services:
  reverse-proxy:
    restart: unless-stopped
    image: nginx:alpine
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./certificates:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - my-network
    depends_on:
      - backend

  backend:
    image: cv-backend-prod
    build:
      context: backend
      dockerfile: docker/Dockerfile-prod
    networks:
      - my-network
    restart: always
    environment:
      - NODE_ENV=production
