services:
  frontend:
    image: cv-frontend-dev
    build:
      context: frontend
      dockerfile: docker/Dockerfile-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=development
    networks:
      - my-network
    depends_on:
      - backend

  backend:
    image: cv-backend-dev
    build:
      context: backend
      dockerfile: docker/Dockerfile-dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development
    networks:
      - my-network

networks:
  my-network:
