# Use offical Node.js image
FROM node:22

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .

# Install global ts-node & typescript
RUN npm install -g ts-node typescript

EXPOSE 8000

# Lauch Vite in dev mode
CMD ["npm", "run", "dev"]