# Use offical Node.js image
FROM node:22 AS builder

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --only=production
COPY ./dist ./dist

EXPOSE 8000

# Lauch the app
CMD ["node", "dist/index.js"]