FROM node:22 AS builder

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --only=production
COPY . .
RUN npm run build

# Use offical Node.js image based on Alpine to reduce image size
FROM node:22-alpine AS runner

WORKDIR /usr/src/app
COPY .env.prod .env
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist

EXPOSE 8000

# Lauch the app
CMD ["node", "dist/index.js"]